port: 7880
rtc:
  port_range_start: 50000
  port_range_end: 59999
  use_external_ip: true
  
keys:
  devkey: FdbkqmLYwi5nEgfnO60VFm+YZLCMFq5Vi8bR97w3xcU=
  secret: Q+4Vdu3IePNr0/dqtVsLdC8arWSSPPJW61pA4W+ilMU=

room:
  auto_create: true
  empty_timeout: 300
  max_participants: 20

logging:
  level: info
